spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/tekhoufeha_auth_db
    username: root
    password: TekhouFeha@2026
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 4f6c8d0e5a1b9c7d3e2f8a6b1c9d4e7f5a8b2c6d9e1f3a7b4c8d0e5f1a9b3c7
  expiration: 86400000

server:
  port: 8081