spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  mail:
    host: smtp.gmail.com
    port: 587
    username: khalildridi859@gmail.com
    password: kspf lety dfzx vlfn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/tekhoufeha_auth_db
    username: root
    password: TekhouFeha@2026
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration


email-verification:
  expiration: 86400000
password-reset:
  expiration: 3600000


jwt:
  secret: 4f6c8d0e5a1b9c7d3e2f8a6b1c9d4e7f5a8b2c6d9e1f3a7b4c8d0e5f1a9b3c7
  expiration: 86400000


refresh-token:
  expiration: 604800000


server:
  port: 8081